name: Json Rest Server
port: 8080
# host: 0.0.0.0
host: 192.168.15.7
database: database.json

auth:
  jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
  jwtExpire: 3600
  unauthorizedStatusCode: 401
  urlSkip:
    - /users:
       method: get    
    - /products:
       method: get 
    - /products/{*}:
       method: get
    - /user-register:
       method: post
    - /user-register:
       method: get